name: Build PDF Splitter App

on:
  push:
#    paths:
#      - 'split_pdf_files/**'
    branches:
      - main
  pull_request:
    paths:
      - 'split_pdf_files/**'
    branches:
      - main

jobs:
  test:
    name: Run Tests
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.12.6'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r split_pdf_files/requirements.txt
        
    - name: Run tests
      run: |
        cd split_pdf_files
        pytest tests/ -v

  build:
    needs: test
    name: Build for ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest, macos-latest, ubuntu-latest]
        python-version: ['3.12.6']

    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r split_pdf_files/requirements.txt
        pip install pyinstaller

    - name: Install Linux dependencies
      if: matrix.os == 'ubuntu-latest'
      run: |
        sudo apt-get update
        sudo apt-get install -y python3-tk

    - name: Build executable (Windows)
      if: matrix.os == 'windows-latest'
      run: |
        cd split_pdf_files
        $tkpath = python -c "import tkinter,os;print(os.path.dirname(tkinter.__file__))"
        pyinstaller --name "PDF Splitter" --windowed --onefile --add-data "$tkpath;tkinter" --hidden-import PyPDF2 --hidden-import tkinter --hidden-import tkinter.ttk --hidden-import tkinter.filedialog gui.py

    - name: Build executable (macOS)
      if: matrix.os == 'macos-latest'
      run: |
        cd split_pdf_files
        pyinstaller --windowed --name "PDF Splitter" --add-data "$(python -c 'import tkinter; print(tkinter.__file__)'):./tkinter" --hidden-import PyPDF2 --hidden-import tkinter --hidden-import tkinter.ttk --hidden-import tkinter.filedialog gui.py

    - name: Build executable (Linux)
      if: matrix.os == 'ubuntu-latest'
      run: |
        cd split_pdf_files
        tkpath=$(python -c 'import tkinter; print(tkinter.__file__)')
        pyinstaller --name "PDF Splitter" --windowed --onefile --add-data "$tkpath:tkinter" --hidden-import PyPDF2 --hidden-import tkinter --hidden-import tkinter.ttk --hidden-import tkinter.filedialog gui.py

    - name: Upload artifacts
      uses: actions/upload-artifact@v3
      with:
        name: PDF-Splitter-${{ matrix.os }}
        path: |
          split_pdf_files/dist/*
        retention-days: 7